name: "pre_release"

on:
  push:
    branches:
      - master_TEMP_DISABLE

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install build.
      run: |
        python -m pip install --upgrade pip
        python -m pip install build --user
    - name: Build binary.
      run: |
        python -m build --sdist --wheel --outdir dist/
    - name: Upload pre-release.
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
